// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using option_one.Data;

namespace option_one.Migrations
{
    [DbContext(typeof(PromoCodesDBContext))]
    [Migration("20210325010650_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("option_one.Models.Services", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("service_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ServiceDesc")
                        .HasColumnName("service_desc")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("ServicePromocode")
                        .HasColumnName("service_promocode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ServiceStatus")
                        .HasColumnName("service_status")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ServiceTitle")
                        .HasColumnName("service_title")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            ServiceDesc = "Siteconstructor decription",
                            ServicePromocode = "SiteconstructorPromocode",
                            ServiceStatus = "Inactive",
                            ServiceTitle = "Siteconstructor"
                        },
                        new
                        {
                            ServiceId = 2,
                            ServiceDesc = "Appvision description",
                            ServicePromocode = "Appvisionpromocode",
                            ServiceStatus = "Inactive",
                            ServiceTitle = "Appvision.com"
                        },
                        new
                        {
                            ServiceId = 3,
                            ServiceDesc = "Analytics decription",
                            ServicePromocode = "Analyticspromocode",
                            ServiceStatus = "Inactive",
                            ServiceTitle = "Analytics.com"
                        },
                        new
                        {
                            ServiceId = 4,
                            ServiceDesc = "Logotype decription",
                            ServicePromocode = "Logotypepromocode",
                            ServiceStatus = "Inactive",
                            ServiceTitle = "Logotype"
                        });
                });

            modelBuilder.Entity("option_one.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("user_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnName("user_name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            password = "Password1",
                            username = "User1"
                        },
                        new
                        {
                            userId = 2,
                            password = "Password2",
                            username = "User2"
                        },
                        new
                        {
                            userId = 3,
                            password = "Password3",
                            username = "User3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
